final_project/IronTrip/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trip_planners#home'

  resources :trip_planners do
    collection do
      post 'add_venue', to: 'trip_planners#add_venue'
      post 'remove_venue', to: 'trip_planners#remove_venue'

      post 'add_event', to: 'trip_planners#add_event'
      post 'remove_event', to: 'trip_planners#remove_event'

      post 'add_schedule', to: 'trip_planners#add_schedule'

      get 'itenarary'
    end
  end

  resources :schedules

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final_project/IronTrip/app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :trip_planners
  has_many :scheduled_trip_planners, through: :schedules, source: :trip_planners
  has_many :schedules
end

final_project/IronTrip/app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :trip_planner
  belongs_to :venue
  belongs_to :event
end

final_project/IronTrip/app/models/trip_planner.rb
class TripPlanner < ApplicationRecord
  has_and_belongs_to_many :venues
  has_and_belongs_to_many :events
  has_many :schedules
  has_many :scheduled_venues, through: :schedules, source: :venue
  has_many :scheduled_events, through: :schedules, source: :event

end

final_project/IronTrip/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

final_project/IronTrip/app/models/venue.rb
class Venue < ApplicationRecord
  has_and_belongs_to_many :trip_planners
  has_many :scheduled_trip_planners, through: :schedules, source: :trip_planners
  has_many :schedules
end

final_project/IronTrip/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  before_action :authenticate_user!
end

final_project/IronTrip/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

end

final_project/IronTrip/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

final_project/IronTrip/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
end

final_project/IronTrip/app/controllers/trip_planners_controller.rb
class TripPlannersController < ApplicationController
  before_action :initialize_session_cart

  def initialize_session_cart
    session[:cart] ||= ActiveSupport::HashWithIndifferentAccess.new
    session[:cart]['venues'] ||= []
    session[:cart]['events'] ||= []
    session[:cart][:schedule] ||= {}
    session[:cart][:schedule]['venue'] ||= {}
    session[:cart][:schedule]['event'] ||= {}
  end

  def home
  end

  def create
    date = "#{params["start_date(1i)"]}/#{params["start_date(2i)"]}/#{params["start_date(3i)"]}"
    @trip = TripPlanner.new(start_date: date)
    @venues = Venue.where(id: session[:cart]['venues'])
    @events = Event.where(id: session[:cart]['events'])
    @trip.venues = @venues
    @trip.events = @events

    if @trip.save
      session[:cart][:schedule]['venue'].each do |key, value|
        Schedule.create(trip_planner_id: @trip.id, venue_id: key, day: value['day'], time: value['time'])
      end
      session[:cart][:schedule]['event'].each do |key, value|
        Schedule.create(trip_planner_id: @trip.id, event_id: key, day: value['day'], time: value['time'])
      end
      session[:cart][:schedule]['venue'] = {}
      session[:cart][:schedule]['event'] = {}
      session[:cart] = ActiveSupport::HashWithIndifferentAccess.new
      session[:cart]['venues'] = []
      session[:cart]['events'] = []
      redirect_to @trip
    else
      render 'new'
    end
  end

  def show
    if session[:city] != params[:city]
      session[:city] = params[:city]
      venues = RestClient.get 'https://api.foursquare.com/v2/venues/explore?near=' + params[:city] + '&limit=20&client_id=HKRLGM2CST1LW4BA41XANSRU5PHQH1BN3OMAHKEUDIUXGRJ5&client_secret=XJ2E1RJDNXXH3YAXRCOH30V4EO5BYLEVZZH20HMGC3NQ302K&v=20160804'
      json = JSON.parse(venues.body)
      if json['response']['groups'][0]['items'].any?
        json['response']['groups'][0]['items'].each do |venue|
          v = Venue.find_or_initialize_by(api_id: venue['venue']['id'])
          v.update_attributes(name: venue['venue']['name'],
          address: venue['venue']['location']['address'],
          category: venue['venue']['categories'][0]['name'],
          city: venue['venue']['location']['city'].downcase,
          api_id: venue['venue']['id'],
          image: venue['tips'].first['photourl'] || 'venue_avatar.png')
        end
      end
      events = RestClient.get 'http://api.eventful.com/json/events/search?app_key=DTvpFhpWPB3xrVQK&image_sizes=large,block200&sort_order=popularity&page_size=20&location=' + params[:city]
      json = JSON.parse(events.body)
      if json['events']['event'].any?
        json['events']['event'].each do |event|
          e = Event.find_or_initialize_by(api_id: event['id'])
          if event['image'] != nil
            e.update_attributes(title: event['title'], location: event['venue_name'],
            date: event['start_time'], city_name: event['city_name'].downcase,
            location: event['venue_name'], date: event['start_time'],
            image: event['image']['large']['url'])
          else
            e.update_attributes(title: event['title'], location: event['venue_name'],
            date: event['start_time'], city_name: event['city_name'].downcase,
            location: event['venue_name'], date: event['start_time'],
            image: 'event_avatar.png')
          end
        end
      end
    end

    @venues = Venue.where(city: params[:city].downcase)
    @events = Event.where(city_name: params[:city].downcase)
  end

  def new
    @trip = TripPlanner.new
    @venues = Venue.where(id: session[:cart]['venues'])
    @events = Event.where(id: session[:cart]['events'])
  end

  def add_venue
    session[:cart]['venues'].push(params[:venue_id]) unless session[:cart]['venues'].include?(params[:venue_id])
    redirect_to :back
  end

  def remove_venue
    session[:cart]['venues'].delete(params[:venue_id])
    redirect_to :back
  end

  def add_event
    session[:cart]['events'].push(params[:event_id]) unless session[:cart]['events'].include?(params[:event_id])
    redirect_to :back
  end

  def remove_event
    session[:cart]['events'].delete(params[:evet_id])
    redirect_to :back
  end

  def itenarary
  end

  def add_schedule
    session[:cart][:schedule][params[:type]][params[:id]] = {day: params[:day], time: params[:time]}
  end

end

final_project/IronTrip/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  # def index
  #   @venues = Venue.all
  # end

end

final_project/IronTrip/app/helpers/events_helper.rb
module EventsHelper
end

final_project/IronTrip/app/helpers/schedules_helper.rb
module SchedulesHelper
end

final_project/IronTrip/app/helpers/trip_planners_helper.rb
module TripPlannersHelper
end

final_project/IronTrip/app/helpers/venues_helper.rb
module VenuesHelper
end

final_project/IronTrip/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IronTrip</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'  %>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  </head>

  <body id=<%=params[:controller]%>-<%=params[:action]%>>
    <% if user_signed_in? %>
      <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="/">IRONTRIP</a>
        </div>

        <form class="navbar-form navbar-left" action="trip_planners/show" method="get">
          <div class="form-group">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="city" id="search-box">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
          </div>
        </form>

        <div class="collapse navbar-collapse navbar-right" id="navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to('Search', root_path) %></li>
            <li><%= link_to('Planner', new_trip_planner_path) %></li>
            <li><%= link_to('Itenerary', itenarary_trip_planners_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </div>
      </div>
    <% end %>

    <!-- <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <div class="pull-left icons">
            <% if user_signed_in? %>
            <div id="home" class="pull-left"><%= link_to('Home', root_path) %></div>
              <% if params[:controller] != 'trip_planner' && params[:action] != 'home' %>
                <div class="pull-right" id="search-box-header">
                  <%= form_tag('show', method: :get, placeholder: 'Enter your destination') do %>
                    <%= text_field_tag(:query) %>
                    <%= submit_tag('Search') %>
                  <% end %>
                </div>
              <% end %>
              <div id="logout" class="pull-left"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></div>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6">
          <% if user_signed_in? && params[:controller] != 'trip_planner' && params[:action] != 'home'%>
            <div id="luggage" class="pull-right">
              <%= link_to(image_tag('bag.png', class: 'bag'), new_trip_planner_path) %>
            </div>
          <% end %>
        </div>
      </div>
    </div> -->

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>